### PR TITLE
Adding new Linux OS Domain Managers

### PR DESCRIPTION
**Pull request by Future998**
Two Linux OS managers have been added:
- Linux Active Directory OS Manager,
- FreeIPA Linux OS Manager.

The machine is joined to the domain using the realm utility, so you need to add a dependency to the actor on this utility. It was chosen because it works in various Linux distributions, so it is universal.

### CODE REVIEW

**Comment by dkmstr** [comment]
Thank you very much!!
I'll add "realmd" as an optional dependency on debian-based package, and look for the package dependency for RPM (if you know it's name, it's welcome :) )

Regards

**Comment by dkmstr** [comment]
Thank you very much.
I have been reviewing the code, and, if you don't mind, i'll fix some elements.
UDS now has an "auto serialization" (since a lot time ago in fact), so mashal and unmarshal are normally only used on "legacy" code only.

I'll fix it and commit it, it's a very simple change (basically, delete some things and rename others), 

Again, thanks for the contribution. :)

**Comment by Future998** [comment]
I am grateful for the code review.

Regards

**Comment by Future998** [comment]
I have a couple of questions left. Is it necessary to backport these changes to the 3.6 branch? And is a 3.6.1 release planned?

Regards

**Pull request merged**
